=== lordheavy/headoverheels/src/csxml/configuration.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="configuration" type="ConfigurationXML"/>
  <xsd:complexType name="ConfigurationXML">
    <xsd:sequence>
      <xsd:element name="language" type="xsd:string"/>
      <xsd:element name="keyboard">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="left" type="xsd:int"/>
            <xsd:element name="right" type="xsd:int"/>
            <xsd:element name="up" type="xsd:int"/>
            <xsd:element name="down" type="xsd:int"/>
            <xsd:element name="take" type="xsd:int"/>
            <xsd:element name="jump" type="xsd:int"/>
            <xsd:element name="shoot" type="xsd:int"/>
            <xsd:element name="takeandjump" type="xsd:int"/>
            <xsd:element name="swap" type="xsd:int"/>
            <xsd:element name="halt" type="xsd:int"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="volume">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="fx" type="xsd:int"/>
            <xsd:element name="music" type="xsd:int"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== lordheavy/headoverheels/gamedata/configuration.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="configuration.xsd">

  <language></language>

  <keyboard>
    <left>82</left>
    <right>83</right>
    <up>84</up>
    <down>85</down>
    <take>13</take>
    <jump>75</jump>
    <shoot>14</shoot>
    <takeandjump>2</takeandjump>
    <swap>26</swap>
    <halt>59</halt>
  </keyboard>

  <volume>
    <fx>75</fx>
    <music>99</music>
  </volume>

</configuration>
