=== lordheavy/headoverheels/src/csxml/items.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="items" type="ItemsXML"/>
  <xsd:complexType name="ItemsXML">
    <xsd:sequence>
      <xsd:element name="item" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="door" minOccurs="0">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:enumeration value="north"/>
                  <xsd:enumeration value="south"/>
                  <xsd:enumeration value="east"/>
                  <xsd:enumeration value="west"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
            <xsd:element name="widthX" type="xsd:int" maxOccurs="3"/>
            <xsd:element name="widthY" type="xsd:int" maxOccurs="3"/>
            <xsd:element name="height" type="xsd:int" maxOccurs="3"/>
            <xsd:element name="directionFrames" type="xsd:byte"/>
            <xsd:element name="mortal" type="xsd:boolean"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="framesDelay" type="xsd:double"/>
            <xsd:element name="speed" type="xsd:double"/>
            <xsd:element name="bitmap">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="frameWidth" type="xsd:int"/>
                  <xsd:element name="frameHeight" type="xsd:int"/>
                </xsd:sequence>
                <xsd:attribute name="file" type="xsd:string" use="required"/>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="shadow" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="shadowWidth" type="xsd:int"/>
                  <xsd:element name="shadowHeight" type="xsd:int"/>
                </xsd:sequence>
                <xsd:attribute name="file" type="xsd:string" use="required"/>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="extraFrames" type="xsd:int" minOccurs="0"/>
            <xsd:element name="frame" type="xsd:int" maxOccurs="unbounded"/>
          </xsd:sequence>
          <xsd:attribute name="label" type="xsd:short" use="required"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== lordheavy/headoverheels/gamedata/items.xml
<?xml version="1.0" encoding="UTF-8"?>

<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="items.xsd">

  <!-- Brick #1 -->
  <item label="1">
    <widthX>16</widthX>
    <widthY>16</widthY>
    <height>24</height>
    <directionFrames>1</directionFrames>
    <mortal>false</mortal>
    <weight>0.032</weight>
    <framesDelay>0</framesDelay>
    <speed>0</speed>
    <bitmap file="gfx/item/brick1.bmp">
      <frameWidth>64</frameWidth>
      <frameHeight>56</frameHeight>
    </bitmap>
    <shadow file="gfx/item/brick1-shadows.bmp">
      <shadowWidth>64</shadowWidth>
      <shadowHeight>31</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Vulcano -->
  <item label="2">
    <widthX>16</widthX>
    <widthY>16</widthY>
    <height>24</height>
    <directionFrames>1</directionFrames>
    <mortal>true</mortal>
    <weight>0</weight>
    <framesDelay>0</framesDelay>
    <speed>0</speed>
    <bitmap file="gfx/item/vulcano.bmp">
      <frameWidth>64</frameWidth>
      <frameHeight>56</frameHeight>
    </bitmap>
    <shadow file="gfx/item/vulcano-shadows.bmp">
      <shadowWidth>64</shadowWidth>
      <shadowHeight>31</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>

  <!-- Spikes -->
  <item label="3">
    <widthX>16</widthX>
    <widthY>16</widthY>
    <height>24</height>
    <directionFrames>1</directionFrames>
    <mortal>true</mortal>
    <weight>0</weight>
    <framesDelay>0</framesDelay>
    <speed>0</speed>
    <bitmap file="gfx/item/spikes.bmp">
      <frameWidth>64</frameWidth>
      <frameHeight>56</frameHeight>
    </bitmap>
    <shadow file="gfx/item/spikes-shadows.bmp">
      <shadowWidth>64</shadowWidth>
      <shadowHeight>31</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Toaster -->
  <item label="4">
    <widthX>16</widthX>
    <widthY>16</widthY>
    <height>24</height>
    <directionFrames>2</directionFrames>
    <mortal>true</mortal>
    <weight>0</weight>
    <framesDelay>0</framesDelay>
    <speed>0</speed>
    <bitmap file="gfx/item/toaster.bmp">
      <frameWidth>64</frameWidth>
      <frameHeight>56</frameHeight>
    </bitmap>
    <shadow file="gfx/item/toaster-shadows.bmp">
      <shadowWidth>64</shadowWidth>
      <shadowHeight>31</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Conveyor belt -->
  <item label="5">
    <widthX>16</widthX>
    <widthY>16</widthY>
    <height>24</height>
    <directionFrames>4</directionFrames>
    <mortal>false</mortal>
    <weight>0</weight>
    <framesDelay>0</framesDelay>
    <speed>0.040</speed>
    <bitmap file="gfx/item/conveyor-belt.bmp">
      <frameWidth>64</frameWidth>
      <frameHeight>56</frameHeight>
    </bitmap>
    <shadow file="gfx/item/conveyor-belt-shadows.bmp">
      <shadowWidth>64</shadowWidth>
      <shadowHeight>31</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Book -->
  <item label="6">
    <widthX>16</widthX>
    <widthY>16</widthY>
    <height>24</height>
    <directionFrames>2</directionFrames>
    <mortal>false</mortal>
    <weight>0.020</weight>
    <framesDelay>0</framesDelay>
    <speed>0.040</speed>
    <bitmap file="gfx/item/book.bmp">
      <frameWidth>64</frameWidth>
      <frameHeight>56</frameHeight>
    </bitmap>
    <shadow file="gfx/item/book-shadows.bmp">
      <shadowWidth>64</shadowWidth>
      <shadowHeight>31</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Stool -->
  <item label="7">
    <widthX>16</widthX>
    <widthY>16</widthY>
    <height>24</height>
    <directionFrames>4</directionFrames>
    <mortal>false</mortal>
    <weight>0.020</weight>
    <framesDelay>0</framesDelay>
    <speed>0.040</speed>
    <bitmap file="gfx/item/stool.bmp">
      <frameWidth>64</frameWidth>
      <frameHeight>56</frameHeight>
    </bitmap>
    <shadow file="gfx/item/stool-shadows.bmp">
      <shadowWidth>64</shadowWidth>
      <shadowHeight>31</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Puppy -->
  <item label="8">
    <widthX>16</widthX>
    <widthY>16</widthY>
    <height>24</height>
    <directionFrames>2</directionFrames>
    <mortal>false</mortal>
    <weight>0</weight>
    <framesDelay>0</framesDelay>
    <speed>0</speed>
    <bitmap file="gfx/item/puppy.bmp">
      <frameWidth>64</frameWidth>
      <frameHeight>56</frameHeight>
    </bitmap>
    <shadow file="gfx/item/puppy-shadows.bmp">
      <shadowWidth>64</shadowWidth>
      <shadowHeight>31</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Sandwich -->
  <item label="9">
    <widthX>15</widthX>
    <widthY>15</widthY>
    <height>24</height>
    <directionFrames>4</directionFrames>
    <mortal>false</mortal>
    <weight>0.010</weight>
    <framesDelay>0</framesDelay>
    <speed>0.040</speed>
    <bitmap file="gfx/item/sandwich.bmp">
      <frameWidth>64</frameWidth>
      <frameHeight>56</frameHeight>
    </bitmap>
    <shadow file="gfx/item/sandwich-shadows.bmp">
      <shadowWidth>64</shadowWidth>
      <shadowHeight>31</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>

  <!-- Switch -->
  <item label="10">
    <widthX>12</widthX>
    <widthY>12</widthY>
    <height>24</height>
    <directionFrames>1</directionFrames>
    <mortal>false</mortal>
    <weight>0</weight>
    <framesDelay>0</framesDelay>
    <speed>0</speed>
    <bitmap file="gfx/item/switch.bmp">
      <frameWidth>48</frameWidth>
      <frameHeight>48</frameHeight>
    </bitmap>
    <shadow file="gfx/item/switch-shadows.bmp">
      <shadowWidth>48</shadowWidth>
      <shadowHeight>25</shadowHeight>
    </shadow>
    <frame>0</frame>
    <frame>1</frame>
  </item>
  
  <!-- Brick #2 -->
  <item label="11">
    <widthX>16</widthX>
    <widthY>16</widthY>
    <height>24</height>
    <directionFrames>1</directionFrames>
    <mortal>false</mortal>
    <weight>0.032</weight>
    <framesDelay>0</framesDelay>
    <speed>0</speed>
    <bitmap file="gfx/item/brick2.bmp">
      <frameWidth>64</frameWidth>
      <frameHeight>56</frameHeight>
    </bitmap>
    <shadow file="gfx/item/brick2-shadows.bmp">
      <shadowWidth>64</shadowWidth>
      <shadowHeight>31</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Bars N-S -->
  <item label="12">
    <widthX>8</widthX>
    <widthY>16</widthY>
    <height>24</height>
    <directionFrames>1</directionFrames>
    <mortal>false</mortal>
    <weight>0</weight>
    <framesDelay>0</framesDelay>
    <speed>0</speed>
    <bitmap file="gfx/item/bars-ns.bmp">
      <frameWidth>42</frameWidth>
      <frameHeight>44</frameHeight>
    </bitmap>
    <shadow file="gfx/item/bars-ns-shadows.bmp">
      <shadowWidth>40</shadowWidth>
      <shadowHeight>22</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Bars E-W -->
  <item label="80">
    <widthX>16</widthX>
    <widthY>8</widthY>
    <height>24</height>
    <directionFrames>1</directionFrames>
    <mortal>false</mortal>
    <weight>0</weight>
    <framesDelay>0</framesDelay>
    <speed>0</speed>
    <bitmap file="gfx/item/bars-ew.bmp">
      <frameWidth>42</frameWidth>
      <frameHeight>44</frameHeight>
    </bitmap>
    <shadow file="gfx/item/bars-ew-shadows.bmp">
      <shadowWidth>40</shadowWidth>
      <shadowHeight>22</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Drum -->
  <item label="13">
    <widthX>12</widthX>
    <widthY>12</widthY>
    <height>24</height>
    <directionFrames>1</directionFrames>
    <mortal>false</mortal>
    <weight>0.010</weight>
    <framesDelay>0</framesDelay>
    <speed>0.040</speed>
    <bitmap file="gfx/item/drum.bmp">
      <frameWidth>48</frameWidth>
      <frameHeight>48</frameHeight>
    </bitmap>
    <shadow file="gfx/item/drum-shadows.bmp">
      <shadowWidth>48</shadowWidth>
      <shadowHeight>25</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Portable brick -->
  <item label="14">
    <widthX>12</widthX>
    <widthY>12</widthY>
    <height>24</height>
    <directionFrames>1</directionFrames>
    <mortal>false</mortal>
    <weight>0.010</weight>
    <framesDelay>0</framesDelay>
    <speed>0.040</speed>
    <bitmap file="gfx/item/portable-brick.bmp">
      <frameWidth>48</frameWidth>
      <frameHeight>48</frameHeight>
    </bitmap>
    <shadow file="gfx/item/portable-brick-shadows.bmp">
      <shadowWidth>48</shadowWidth>
      <shadowHeight>25</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Donuts -->
  <item label="15">
    <widthX>12</widthX>
    <widthY>12</widthY>
    <height>24</height>
    <directionFrames>2</directionFrames>
    <mortal>false</mortal>
    <weight>0.010</weight>
    <framesDelay>0</framesDelay>
    <speed>0</speed>
    <bitmap file="gfx/item/donuts.bmp">
      <frameWidth>48</frameWidth>
      <frameHeight>48</frameHeight>
    </bitmap>
    <shadow file="gfx/item/donuts-shadows.bmp">
      <shadowWidth>48</shadowWidth>
      <shadowHeight>25</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
  
  <!-- Rabbit (extra life) -->
  <item label="16">
    <widthX>12</widthX>
    <widthY>12</widthY>
    <height>24</height>
    <directionFrames>2</directionFrames>
    <mortal>false</mortal>
    <weight>0.010</weight>
    <framesDelay>0</framesDelay>
    <speed>0.040</speed>
    <bitmap file="gfx/item/rabbit-gold.bmp">
      <frameWidth>48</frameWidth>
      <frameHeight>48</frameHeight>
    </bitmap>
    <shadow file="gfx/item/rabbit-shadows.bmp">
      <shadowWidth>48</shadowWidth>
      <shadowHeight>25</shadowHeight>
    </shadow>
    <frame>0</frame>
  </item>
