=== lordheavy/headoverheels/src/csxml/map.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="map" type="MapXML"/>
  <xsd:complexType name="MapXML">
    <xsd:sequence>
      <xsd:element name="room" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="north" type="xsd:string" minOccurs="0"/>
            <xsd:element name="south" type="xsd:string" minOccurs="0"/>
            <xsd:element name="east" type="xsd:string" minOccurs="0"/>
            <xsd:element name="west" type="xsd:string" minOccurs="0"/>
            <xsd:element name="north-east" type="xsd:string" minOccurs="0"/>
            <xsd:element name="north-west" type="xsd:string" minOccurs="0"/>
            <xsd:element name="south-east" type="xsd:string" minOccurs="0"/>
            <xsd:element name="south-west" type="xsd:string" minOccurs="0"/>
            <xsd:element name="east-north" type="xsd:string" minOccurs="0"/>
            <xsd:element name="east-south" type="xsd:string" minOccurs="0"/>
            <xsd:element name="west-north" type="xsd:string" minOccurs="0"/>
            <xsd:element name="west-south" type="xsd:string" minOccurs="0"/>
            <xsd:element name="floor" type="xsd:string" minOccurs="0"/>
            <xsd:element name="roof" type="xsd:string" minOccurs="0"/>
            <xsd:element name="teleport" type="xsd:string" minOccurs="0"/>
            <xsd:element name="teleport2" type="xsd:string" minOccurs="0"/>
          </xsd:sequence>
          <xsd:attribute name="file" type="xsd:string" use="required"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== lordheavy/headoverheels/gamedata/map/map.xml
<?xml version="1.0" encoding="UTF-8"?>

<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="map.xsd">

    <!-- Template
    <room file="room.xml">
        <north></north>
        <south></south>
        <east></east>
        <west></west>
        <north-east></north-east>
        <north-west></north-west>
        <south-east></south-east>
        <south-west></south-west>
        <east-north></east-north>
        <east-south></east-south>
        <west-north></west-north>
        <west-south></west-south>
        <floor></floor>
        <roof></roof>
        <teleport></teleport>
    </room>
    -->

    <room file="blacktooth/blacktooth01.xml">
        <south>blacktooth/blacktooth23.xml</south>
        <teleport>blacktooth/blacktooth02.xml</teleport>
    </room>

    <room file="blacktooth/blacktooth02.xml">
        <west>blacktooth/blacktooth03.xml</west>
        <teleport>blacktooth/blacktooth01.xml</teleport>
    </room>

    <room file="blacktooth/blacktooth03.xml">
        <east>blacktooth/blacktooth02.xml</east>
        <floor>blacktooth/blacktooth04.xml</floor>
    </room>

    <room file="blacktooth/blacktooth04.xml">
        <west>blacktooth/blacktooth05.xml</west>
        <roof>blacktooth/blacktooth03.xml</roof>
    </room>

    <room file="blacktooth/blacktooth05.xml">
        <north>blacktooth/blacktooth06.xml</north>
        <east>blacktooth/blacktooth04.xml</east>
        <west>blacktooth/blacktooth07.xml</west>
    </room>

    <room file="blacktooth/blacktooth06.xml">
        <south>blacktooth/blacktooth05.xml</south>
    </room>

    <room file="blacktooth/blacktooth07.xml">
        <north>blacktooth/blacktooth10.xml</north>
        <east>blacktooth/blacktooth05.xml</east>
        <west>blacktooth/blacktooth08.xml</west>
    </room>

    <room file="blacktooth/blacktooth08.xml">
        <south>blacktooth/blacktooth09.xml</south>
        <east>blacktooth/blacktooth07.xml</east>
    </room>

    <room file="blacktooth/blacktooth09.xml">
        <north>blacktooth/blacktooth08.xml</north>
    </room>

    <room file="blacktooth/blacktooth10.xml">
        <north>blacktooth/blacktooth11.xml</north>
        <south>blacktooth/blacktooth07.xml</south>
    </room>

    <room file="blacktooth/blacktooth11.xml">
        <north>blacktooth/blacktooth12.xml</north>
        <south>blacktooth/blacktooth10.xml</south>
        <east>blacktooth/blacktooth32.xml</east>
        <west>blacktooth/blacktooth31.xml</west>
    </room>

    <room file="blacktooth/blacktooth12.xml">
        <north>blacktooth/blacktooth13.xml</north>
        <south>blacktooth/blacktooth11.xml</south>
    </room>

    <room file="blacktooth/blacktooth13.xml">
        <north>blacktooth/blacktooth14.xml</north>
        <south>blacktooth/blacktooth12.xml</south>
        <east>blacktooth/blacktooth15.xml</east>
    </room>

    <room file="blacktooth/blacktooth14.xml">
        <south>blacktooth/blacktooth13.xml</south>
    </room>

    <room file="blacktooth/blacktooth15.xml">
        <east>blacktooth/blacktooth16.xml</east>
        <west>blacktooth/blacktooth13.xml</west>
    </room>

    <room file="blacktooth/blacktooth16.xml">
        <north>blacktooth/blacktooth17.xml</north>
        <west>blacktooth/blacktooth15.xml</west>
    </room>

    <room file="blacktooth/blacktooth17.xml">
        <north-east>blacktooth/blacktooth18.xml</north-east>
        <north-west>blacktooth/blacktooth19.xml</north-west>
        <south-west>blacktooth/blacktooth16.xml</south-west>
    </room>

    <room file="blacktooth/blacktooth18.xml">
        <north>blacktooth/blacktooth20.xml</north>
        <south>blacktooth/blacktooth17.xml</south>
    </room>

    <room file="blacktooth/blacktooth19.xml">
        <south>blacktooth/blacktooth17.xml</south>
        <east>blacktooth/blacktooth20.xml</east>
    </room>

    <room file="blacktooth/blacktooth20.xml">
        <south>blacktooth/blacktooth18.xml</south>
        <east>blacktooth/blacktooth21.xml</east>
        <west>blacktooth/blacktooth19.xml</west>
    </room>

    <room file="blacktooth/blacktooth21.xml">
        <east>blacktooth/blacktooth22.xml</east>
        <west>blacktooth/blacktooth20.xml</west>
    </room>

    <room file="blacktooth/blacktooth22.xml">
        <west>blacktooth/blacktooth21.xml</west>
        <floor>blacktooth/blacktooth44.xml</floor>
    </room>

    <room file="blacktooth/blacktooth23.xml">
        <north>blacktooth/blacktooth01.xml</north>
        <teleport>blacktooth/blacktooth24.xml</teleport>
    </room>

    <room file="blacktooth/blacktooth24.xml">
        <north>blacktooth/blacktooth25.xml</north>
        <teleport>blacktooth/blacktooth23.xml</teleport>
    </room>

    <room file="blacktooth/blacktooth25.xml">
        <south>blacktooth/blacktooth24.xml</south>
        <roof>blacktooth/blacktooth26.xml</roof>
    </room>

    <room file="blacktooth/blacktooth26.xml">
        <east>blacktooth/blacktooth27.xml</east>
        <floor>blacktooth/blacktooth25.xml</floor>
    </room>

    <room file="blacktooth/blacktooth27.xml">
        <south>blacktooth/blacktooth28.xml</south>
        <east>blacktooth/blacktooth29.xml</east>
        <west>blacktooth/blacktooth26.xml</west>
    </room>

    <room file="blacktooth/blacktooth28.xml">
        <north>blacktooth/blacktooth27.xml</north>
    </room>

    <room file="blacktooth/blacktooth29.xml">
        <west>blacktooth/blacktooth27.xml</west>
        <roof>blacktooth/blacktooth30.xml</roof>
    </room>

    <room file="blacktooth/blacktooth30.xml">
        <south>blacktooth/blacktooth31.xml</south>
        <floor>blacktooth/blacktooth29.xml</floor>
    </room>

    <room file="blacktooth/blacktooth31.xml">
        <north>blacktooth/blacktooth30.xml</north>
        <east>blacktooth/blacktooth11.xml</east>
    </room>

    <room file="blacktooth/blacktooth32.xml">
        <east>blacktooth/blacktooth33.xml</east>
        <west>blacktooth/blacktooth11.xml</west>
    </room>

    <room file="blacktooth/blacktooth33.xml">
        <west>blacktooth/blacktooth32.xml</west>
        <roof>blacktooth/blacktooth34.xml</roof>
    </room>

    <room file="blacktooth/blacktooth34.xml">
        <east>blacktooth/blacktooth35.xml</east>
        <floor>blacktooth/blacktooth33.xml</floor>
    </room>

    <room file="blacktooth/blacktooth35.xml">
        <north>blacktooth/blacktooth36.xml</north>
        <west>blacktooth/blacktooth34.xml</west>
    </room>

    <room file="blacktooth/blacktooth36.xml">
        <south>blacktooth/blacktooth35.xml</south>
        <east>blacktooth/blacktooth37.xml</east>
    </room>

    <room file="blacktooth/blacktooth37.xml">
        <east>blacktooth/blacktooth38.xml</east>
        <west>blacktooth/blacktooth36.xml</west>
    </room>

    <room file="blacktooth/blacktooth38.xml">
        <west>blacktooth/blacktooth37.xml</west>
        <floor>blacktooth/blacktooth39.xml</floor>
    </room>

    <room file="blacktooth/blacktooth39.xml">
        <north>blacktooth/blacktooth41.xml</north>
        <east>blacktooth/blacktooth40.xml</east>
        <roof>blacktooth/blacktooth38.xml</roof>
    </room>

    <room file="blacktooth/blacktooth40.xml">
        <west>blacktooth/blacktooth39.xml</west>
    </room>

    <room file="blacktooth/blacktooth41.xml">
        <north>blacktooth/blacktooth42.xml</north>
        <south>blacktooth/blacktooth39.xml</south>
    </room>

    <room file="blacktooth/blacktooth42.xml">
        <north>blacktooth/blacktooth43.xml</north>
        <south>blacktooth/blacktooth41.xml</south>
    </room>

    <room file="blacktooth/blacktooth43.xml">
        <south>blacktooth/blacktooth42.xml</south>
        <floor>blacktooth/blacktooth46.xml</floor>
    </room>

    <room file="blacktooth/blacktooth44.xml">
        <south>blacktooth/blacktooth45.xml</south>
        <roof>blacktooth/blacktooth22.xml</roof>
    </room>

    <room file="blacktooth/blacktooth45.xml">
        <north>blacktooth/blacktooth44.xml</north>
        <east>blacktooth/blacktooth46.xml</east>
    </room>

    <room file="blacktooth/blacktooth46.xml">
        <east>blacktooth/blacktooth47.xml</east>
        <west>blacktooth/blacktooth45.xml</west>
        <roof>blacktooth/blacktooth43.xml</roof>
    </room>

    <room file="blacktooth/blacktooth47.xml">
        <east>blacktooth/blacktooth48.xml</east>
        <west>blacktooth/blacktooth46.xml</west>
    </room>

    <room file="blacktooth/blacktooth48.xml">
        <north>blacktooth/blacktooth49.xml</north>
        <west>blacktooth/blacktooth47.xml</west>
    </room>

    <room file="blacktooth/blacktooth49.xml">
        <north>blacktooth/blacktooth50.xml</north>
        <south>blacktooth/blacktooth48.xml</south>
    </room>

    <room file="blacktooth/blacktooth50.xml">
        <north>blacktooth/blacktooth52.xml</north>
        <south>blacktooth/blacktooth49.xml</south>
        <west>blacktooth/blacktooth51.xml</west>
    </room>

    <room file="blacktooth/blacktooth51.xml">
        <east>blacktooth/blacktooth50.xml</east>
        <teleport>moonbase/moonbase01.xml</teleport>
    </room>

    <room file="blacktooth/blacktooth52.xml">
        <south>blacktooth/blacktooth50.xml</south>
        <east>blacktooth/blacktooth53.xml</east>
    </room>

    <room file="blacktooth/blacktooth53.xml">
        <east>blacktooth/blacktooth54.xml</east>
        <west>blacktooth/blacktooth52.xml</west>
    </room>

    <room file="blacktooth/blacktooth54.xml">
        <west>blacktooth/blacktooth53.xml</west>
        <floor>blacktooth/blacktooth55.xml</floor>
    </room>

    <room file="blacktooth/blacktooth55.xml">
        <south>blacktooth/blacktooth56.xml</south>
