=== lordheavy/headoverheels/src/csxml/room.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="room" type="RoomXML"/>
  <xsd:complexType name="RoomXML">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="scenery" type="xsd:string"/>
      <xsd:element name="xTiles" type="xsd:int"/>
      <xsd:element name="yTiles" type="xsd:int"/>
      <xsd:element name="width" type="xsd:int"/>
      <xsd:element name="floorType">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="none"/>
            <xsd:enumeration value="regular"/>
            <xsd:enumeration value="mortal"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="deltaX" type="xsd:int" minOccurs="0"/>
      <xsd:element name="deltaY" type="xsd:int" minOccurs="0"/>
      <xsd:element name="triple-room-data" minOccurs="0">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="northeast" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="southeast" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="northwest" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="southwest" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="eastnorth" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="eastsouth" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="westnorth" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="westsouth" minOccurs="0">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="bound-x">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="minimum" type="xsd:int"/>
                  <xsd:element name="maximum" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
            <xsd:element name="bound-y">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="minimum" type="xsd:int"/>
                  <xsd:element name="maximum" type="xsd:int"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="floor">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="tile" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="x" type="xsd:int"/>
                  <xsd:element name="y" type="xsd:int"/>
                  <xsd:element name="offsetX" type="xsd:int"/>
                  <xsd:element name="offsetY" type="xsd:int"/>
                  <xsd:element name="bitmap" type="xsd:string"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="walls" minOccurs="0">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="wall" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="axis">
                    <xsd:simpleType>
                      <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="x"/>
                        <xsd:enumeration value="y"/>
                      </xsd:restriction>
                    </xsd:simpleType>
                  </xsd:element>
                  <xsd:element name="index" type="xsd:int"/>
                  <xsd:element name="bitmap" type="xsd:string"/>
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="items">
        <xsd:complexType>
          <xsd:sequence>
          <xsd:element name="item" maxOccurs="unbounded">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="label" type="xsd:short"/>
                <xsd:element name="direction">
                  <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                      <xsd:enumeration value="none"/>
                      <xsd:enumeration value="south"/>
                      <xsd:enumeration value="west"/>
                      <xsd:enumeration value="north"/>
                      <xsd:enumeration value="east"/>
                      <xsd:enumeration value="northeast"/>
                      <xsd:enumeration value="southeast"/>
                      <xsd:enumeration value="southwest"/>
                      <xsd:enumeration value="northwest"/>
                      <xsd:enumeration value="eastnorth"/>
                      <xsd:enumeration value="eastsouth"/>
                      <xsd:enumeration value="westnorth"/>
                      <xsd:enumeration value="westsouth"/>
                    </xsd:restriction>
                  </xsd:simpleType>
                </xsd:element>
                <xsd:element name="behavior" type="xsd:int"/>
                <xsd:element name="type">
                  <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                      <xsd:enumeration value="wall"/>
                      <xsd:enumeration value="door"/>
                      <xsd:enumeration value="griditem"/>
                      <xsd:enumeration value="freeitem"/>
                    </xsd:restriction>
                  </xsd:simpleType>
                </xsd:element>
                <xsd:element name="extra" type="xsd:int" minOccurs="0" maxOccurs="unbounded"/>
              </xsd:sequence>
              <xsd:attribute name="x" type="xsd:int" use="required"/>
              <xsd:attribute name="y" type="xsd:int" use="required"/>
              <xsd:attribute name="z" type="xsd:int" use="required"/>
            </xsd:complexType>
          </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== lordheavy/headoverheels/gamedata/map/egyptus/egyptus16.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<room xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="room.xsd">

  <name>egyptus/egyptus16.xml</name>

  <scenery>egyptus</scenery>

  <xTiles>7</xTiles>

  <yTiles>7</yTiles>

  <width>16</width>

  <floorType>none</floorType>

  <floor>
    <tile>
      <x>0</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-underground-north.bmp</bitmap>
    </tile>
    <tile>
      <x>0</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-underground-north.bmp</bitmap>
    </tile>
    <tile>
      <x>0</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-underground-north.bmp</bitmap>
    </tile>
    <tile>
      <x>0</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-underground-north.bmp</bitmap>
    </tile>
    <tile>
      <x>0</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-underground-north.bmp</bitmap>
    </tile>
    <tile>
      <x>0</x>
      <y>6</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-underground-north.bmp</bitmap>
    </tile>
    <tile>
      <x>3</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-east.bmp</bitmap>
    </tile>
    <tile>
      <x>4</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-east.bmp</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-underground-east.bmp</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-underground-east.bmp</bitmap>
    </tile>
    <tile>
      <x>5</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-underground-east.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-floor-underground-east.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>6</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-west.bmp</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>6</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-west.bmp</bitmap>
    </tile>
    <tile>
      <x>3</x>
      <y>6</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-west.bmp</bitmap>
    </tile>
    <tile>
      <x>4</x>
      <y>6</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-west.bmp</bitmap>
    </tile>
    <tile>
      <x>5</x>
      <y>6</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-west.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>6</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/egyptus/egyptus-nofloor-sw.bmp</bitmap>
    </tile>
  </floor>

  <items>
    <item x="0" y="1" z="0">
      <label>281</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="2" z="0">
      <label>283</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="3" z="0">
      <label>281</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="4" z="0">
      <label>281</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="5" z="0">
      <label>283</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="6" z="0">
      <label>281</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="1" y="0" z="0">
      <label>280</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="2" y="0" z="0">
      <label>280</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="5" y="0" z="0">
      <label>280</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="6" y="0" z="0">
      <label>280</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="3" y="0" z="-1">
      <label>287</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="4" y="0" z="-1">
      <label>287</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="3" y="0" z="-1">
      <label>5055</label>
      <direction>east</direction>
      <behavior>0</behavior>
      <type>door</type>
    </item>
    <item x="1" y="1" z="0">
      <label>11</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="2" y="1" z="0">
      <label>11</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="3" y="1" z="0">
      <label>11</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="4" y="1" z="0">
      <label>11</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="5" y="1" z="0">
      <label>11</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="6" y="1" z="0">
      <label>11</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
  </items>

</room>

=== lordheavy/headoverheels/gamedata/map/safari/safari11.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<room xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="room.xsd">

  <name>safari/safari11.xml</name>

  <scenery>safari</scenery>

  <xTiles>8</xTiles>

  <yTiles>6</yTiles>

  <width>16</width>

  <floorType>regular</floorType>

  <floor>
    <tile>
      <x>0</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor-north.bmp</bitmap>
    </tile>
    <tile>
      <x>0</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor-north.bmp</bitmap>
    </tile>
    <tile>
      <x>7</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>7</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>7</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>7</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>7</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>7</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor-south.bmp</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>1</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>2</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>3</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>3</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>3</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>3</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>3</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>3</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>4</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>4</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>4</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>4</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>4</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>4</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>5</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>5</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>5</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>5</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>5</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>5</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>0</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>1</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>2</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>3</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>4</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
    <tile>
      <x>6</x>
      <y>5</y>
      <offsetX>0</offsetX>
      <offsetY>0</offsetY>
      <bitmap>gfx/safari/safari-floor.bmp</bitmap>
    </tile>
  </floor>

  <walls>
    <wall>
      <axis>x</axis>
      <index>1</index>
      <bitmap>gfx/safari/safari-wall-x-2.bmp</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>2</index>
      <bitmap>gfx/safari/safari-wall-x-1.bmp</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>3</index>
      <bitmap>gfx/safari/safari-wall-x-3.bmp</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>4</index>
      <bitmap>gfx/safari/safari-wall-x-3.bmp</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>5</index>
      <bitmap>gfx/safari/safari-wall-x-1.bmp</bitmap>
    </wall>
    <wall>
      <axis>x</axis>
      <index>6</index>
      <bitmap>gfx/safari/safari-wall-x-2.bmp</bitmap>
    </wall>
  </walls>

  <items>
    <item x="0" y="0" z="0">
      <label>301</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="1" z="0">
      <label>303</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="4" z="0">
      <label>303</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="5" z="0">
      <label>301</label>
      <direction>none</direction>
      <behavior>0</behavior>
      <type>griditem</type>
    </item>
    <item x="0" y="2" z="-1">
      <label>2077</label>
      <direction>north</direction>
      <behavior>0</behavior>
      <type>door</type>
    </item>
    <item x="7" y="2" z="-1">
      <label>3077</label>
      <direction>south</direction>
      <behavior>0</behavior>
      <type>door</type>
    </item>
    <item x="3" y="0" z="0">
      <label>28</label>
      <direction>south</direction>
      <behavior>0</behavior>
      <type>freeitem</type>
    </item>
    <item x="4" y="2" z="0">
      <label>28</label>
      <direction>south</direction>
      <behavior>0</behavior>
      <type>freeitem</type>
    </item>
    <item x="3" y="4" z="0">
      <label>28</label>
      <direction>south</direction>
      <behavior>0</behavior>
      <type>freeitem</type>
    </item>
    <item x="6" y="5" z="0">
      <label>41</label>
      <direction>none</direction>
      <behavior>14</behavior>
      <type>freeitem</type>
    </item>
  </items>

</room>
