=== lordheavy/headoverheels/src/csxml/sounds.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="sounds" type="SoundsXML"/>
  <xsd:complexType name="SoundsXML">
    <xsd:sequence>
      <xsd:element name="item" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="state" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="file" type="xsd:string"/>
                </xsd:sequence>
                <xsd:attribute name="id" type="xsd:string" use="required"/>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
          <xsd:attribute name="label" type="xsd:short" use="required"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== lordheavy/headoverheels/gamedata/sounds.xml
<?xml version="1.0" encoding="UTF-8"?>

<sounds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="sounds.xsd">

  <!-- Brick #1 -->
  <item label="1">
    <state id="destroy">
      <file>sound/destruction.wav</file>
    </state>
    <state id="fall">
      <file>sound/sink.wav</file>
    </state>
  </item>
  
  <!-- Vulcano -->
  
  <!-- Spikes -->
  
  <!-- Toaster -->
  
  <!-- Conveyor belt -->
  <item label="5">
    <state id="active">
      <file>sound/conveyor-belt.wav</file>
    </state>
    <state id="destroy">
      <file>sound/destruction.wav</file>
    </state>
  </item>
  
  <!-- Book -->
  <item label="6">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="collision">
      <file>sound/push.wav</file>
    </state>
    <state id="destroy">
      <file>sound/destruction.wav</file>
    </state>
  </item>
  
  <!-- Stool -->
  <item label="7">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="collision">
      <file>sound/push.wav</file>
    </state>
  </item>
  
  <!-- Puppy -->
  <item label="8">
    <state id="destroy">
      <file>sound/silence-puppy.wav</file>
    </state>
  </item>
  
  <!-- Sandwich -->
  <item label="9">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="collision">
      <file>sound/push.wav</file>
    </state>
  </item>
  
  <!-- Switch -->
  <item label="10">
    <state id="switch">
      <file>sound/switch.wav</file>
    </state>
  </item>
  
  <!-- Brick #2 -->
  <item label="11">
    <state id="destroy">
      <file>sound/destruction.wav</file>
    </state>
    <state id="fall">
      <file>sound/sink.wav</file>
    </state>
  </item>
  
  <!-- Bars N-S -->
  <item label="12">
    <state id="destroy">
      <file>sound/destruction.wav</file>
    </state>
  </item>
  
  <!-- Bars E-W -->
  <item label="80">
    <state id="destroy">
      <file>sound/destruction.wav</file>
    </state>
  </item>
  
  <!-- Drum -->
  <item label="13">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
  </item>
  
  <!-- Portable brick -->
  <item label="14">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
  </item>
  
  <!-- Donuts -->
  <item label="15">
    <state id="destroy">
      <file>sound/tools.wav</file>
    </state>
  </item>
  
  <!-- Rabbit (extra life) -->
  <item label="16">
    <state id="destroy">
      <file>sound/bonus.wav</file>
    </state>
  </item>
  
  <!-- Rabbit (high jump) -->
  <item label="17">
    <state id="destroy">
      <file>sound/bonus.wav</file>
    </state>
  </item>
  
  <!-- Rabbit (high speed) -->
  <item label="18">
    <state id="destroy">
      <file>sound/bonus.wav</file>
    </state>
  </item>
  
  <!-- Rabbit (shield) -->
  <item label="19">
    <state id="destroy">
      <file>sound/bonus.wav</file>
    </state>
  </item>
  
  <!-- Crown -->
  
  <!-- Bomb -->
  <item label="21">
    <state id="move">
      <file>sound/adjust.wav</file>
    </state>
  </item>
  
  <!-- Portable brick #2 -->
  <item label="22">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
  </item>
  
  <!-- Ball -->
  <item label="23">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
  </item>
  
  <!-- Remote control -->
  
  <!-- Brick cylinder -->
  
  <!-- Horn -->
  <item label="26">
    <state id="destroy">
      <file>sound/tools.wav</file>
    </state>
  </item>
  
  <!-- Imperial guard head -->
  
  <!-- Elephant head -->
  
  <!-- Monkey head -->
  
  <!-- Handbag -->
  <item label="30">
    <state id="destroy">
      <file>sound/tools.wav</file>
    </state>
  </item>
  
  <!-- Elevator -->
  <item label="31">
    <state id="move">
      <file>sound/blades.wav</file>
    </state>
  </item>
  
  <!-- Helicopter bug -->
  <item label="32">
    <state id="wait">
      <file>sound/blades.wav</file>
    </state>
    <state id="move">
      <file>sound/blades.wav</file>
    </state>
  </item>
  
  <!-- Reincarnation Fish -->
  <item label="33">
    <state id="destroy">
      <file>sound/bonus.wav</file>
    </state>
  </item>
  
  <!-- Siren -->
  <item label="34">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="collision">
      <file>sound/siren.wav</file>
    </state>
  </item>
  
  <!-- Teleport -->
  <item label="35">
    <state id="active">
      <file>sound/teleport.wav</file>
    </state>
  </item>
  
  <!-- Teleport2 -->
  <item label="83">
    <state id="active">
      <file>sound/teleport.wav</file>
    </state>
  </item>
  
  <!-- Turtle -->
  <item label="36">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="collision">
      <file>sound/gamusino.wav</file>
    </state>
  </item>
  
  <!-- Trampoline -->
  <item label="37">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="active">
      <file>sound/spring.wav</file>
    </state>
  </item>
  
  <!-- Bubbles -->
  
  <!-- Double Bubbles -->
  
  <!-- Mortal cap 39 -->
  
  <!-- Cap 81 -->
  
  <!-- Big head robot -->
  <item label="40">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="collision">
      <file>sound/bighead-robot.wav</file>
    </state>
  </item>
  
  <!-- Elephant -->
  <item label="41">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="collision">
      <file>sound/elephant.wav</file>
    </state>
  </item>
  
  <!-- Monkey -->
  <item label="42">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="collision">
      <file>sound/monkey.wav</file>
    </state>
  </item>
  
  <!-- Diver -->
  <item label="43">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="collision">
      <file>sound/robot-collision.wav</file>
    </state>
  </item>
  
  <!-- Bubble robot -->
  <item label="44">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="collision">
      <file>sound/bubbles-bug.wav</file>
    </state>
  </item>
  
  <!-- Imperial guard -->
  <item label="45">
    <state id="wait">
      <file>sound/imperial-guard.wav</file>
    </state>
  </item>
  
  <!-- Charles -->
  <item label="46">
    <state id="fall">
      <file>sound/fall.wav</file>
    </state>
    <state id="push">
      <file>sound/push.wav</file>
    </state>
    <state id="move">
      <file>sound/robot.wav</file>
    </state>
  </item>
  
  <!-- Dead Fish -->
  
  <!-- Head -->
  <item label="52">
    <state id="move">
      <file>sound/head-walking.wav</file>
    </state>
    <state id="jump">
      <file>sound/head-jumping.wav</file>
    </state>
    <state id="fall">
      <file>sound/head-falling.wav</file>
    </state>
    <state id="destroy">
      <file>sound/hh-dying.wav</file>
    </state>
    <state id="shot">
      <file>sound/shot.wav</file>
    </state>
    <state id="rebound">
      <file>sound/trampoline.wav</file>
    </state>
    <state id="teleport-in">
      <file>sound/teleport-in.wav</file>
    </state>
    <state id="teleport-out">
      <file>sound/teleport-out.wav</file>
    </state>
  </item>
  
  <!-- Heels -->
  <item label="53">
    <state id="move">
      <file>sound/heels-walking.wav</file>
    </state>
    <state id="jump">
      <file>sound/heels-jumping.wav</file>
    </state>
    <state id="fall">
      <file>sound/heels-falling.wav</file>
    </state>
    <state id="destroy">
      <file>sound/hh-dying.wav</file>
    </state>
    <state id="rebound">
      <file>sound/trampoline.wav</file>
    </state>
    <state id="teleport-in">
      <file>sound/teleport-in.wav</file>
    </state>
    <state id="teleport-out">
      <file>sound/teleport-out.wav</file>
    </state>
    <state id="take">
      <file>sound/take.wav</file>
    </state>
    <state id="drop">
      <file>sound/drop.wav</file>
    </state>
    <state id="error">
      <file>sound/error.wav</file>
    </state>
  </item>
  
  <!-- Head over Heels -->
  <item label="55">
    <state id="move">
      <file>sound/heels-walking.wav</file>
    </state>
    <state id="jump">
      <file>sound/head-jumping.wav</file>
    </state>
    <state id="fall">
      <file>sound/head-falling.wav</file>
    </state>
    <state id="destroy">
      <file>sound/hh-dying.wav</file>
    </state>
    <state id="shot">
      <file>sound/shot.wav</file>
    </state>
    <state id="rebound">
      <file>sound/trampoline.wav</file>
    </state>
